### ISSUE TITLE
Define large_datasets in USAGE

### ISSUE THREAD

**Issue by mdesco** [scilus/rbx_flow#13]
@frheault before release, can you give the user an idea of what is a "large_datasets". When should such profile be used?

Also, I remember you use to recommend using nodes with lots lots of RAM, is this still the case? If so, please mention in the USAGE.

**Comment by GuillaumeTh** [comment]
FYI, I never used large memory node to run RBx. And what do you mean about large_datasets ? Big tractograms or number of subjects ?
